import csv, json, random, re
from pathlib import Path

OUT = Path('/mnt/data/insurance-main-trainwork/insurance-main/backend/src/main/resources/ai')
OUT.mkdir(parents=True, exist_ok=True)
random.seed(20260816)

insurance_topics = [
('insurance_basics','insurance','insurance basics','Insurance transfers specified financial risks from a policyholder to an insurer in exchange for premium. The exact protection depends on the policy wording, covered events, limits, deductibles, exclusions, waiting periods, and conditions. A customer should compare both price and protection, disclose material facts accurately, keep proof of payment and policy documents, and contact the insurer when an insured event occurs.'),
('premium','insurance','premium','A premium is the amount paid to keep insurance coverage active. It can depend on the type of insurance, coverage amount, term, age or risk profile, claims history, deductibles, optional riders, and underwriting rules. A lower premium is not always a better deal if the coverage limit is too low or important risks are excluded.'),
('coverage','insurance','coverage','Coverage describes the risks, losses, people, property, or expenses that an insurance policy agrees to protect, subject to its terms. Always check the coverage scope, maximum limit, sub-limits, deductibles, waiting periods, exclusions, and claim requirements instead of relying only on the policy name.'),
('deductible','insurance','deductible','A deductible is the portion of an eligible loss the policyholder pays before the insurer pays the remaining covered amount, subject to policy limits. Higher deductibles often reduce premium but increase out-of-pocket cost when a claim occurs. The policy wording should state whether the deductible applies per claim, per event, or per policy period.'),
('exclusion','insurance','exclusions','An exclusion is a circumstance, cause of loss, treatment, activity, or condition the policy does not cover. Common examples vary by product and can include intentional acts, undeclared pre-existing conditions, wear and tear, illegal activity, war-related risks, or elective procedures. The actual policy wording controls, so customers should review exclusions before purchasing.'),
('waiting_period','insurance','waiting period','A waiting period is a time after coverage starts during which certain benefits are not yet payable. It is common in health, maternity, critical illness, and some other products. The duration and affected benefits vary by plan, and emergency or accident benefits may be treated differently depending on the policy.'),
('claim','insurance','claims','An insurance claim is a formal request for payment or service after a potentially covered event. A good claim process usually includes prompt notification, accurate incident details, required documents, evidence of loss, cooperation with assessment, and tracking the claim status. Final payment depends on coverage, limits, exclusions, policy status, and verification.'),
('underwriting','insurance','underwriting','Underwriting is the insurer’s process for evaluating risk before deciding whether to offer coverage and on what terms. It may consider age, health, occupation, property characteristics, vehicle use, business activity, prior claims, requested limits, and other relevant factors. The final decision can include standard terms, adjusted premium, exclusions, conditions, or decline.'),
('policy_limit','insurance','policy limits','A policy limit is the maximum amount the insurer may pay for a covered loss or during a policy period. Policies can have overall limits and smaller sub-limits for specific benefits. Customers should choose limits based on realistic financial exposure because an insufficient limit can leave a large uncovered balance.'),
('sum_insured','insurance','sum insured','The sum insured or sum assured is a stated coverage amount used to determine the maximum protection for certain benefits. It may influence premium and claim payment, but it does not always mean every claim will be paid up to that amount because deductibles, sub-limits, depreciation, exclusions, and actual loss can apply.'),
('grace_period','insurance','grace period','A grace period is extra time after a premium due date during which payment may still be made under the policy rules. Coverage during this period depends on the contract. If payment is not made by the end of the grace period, the policy can lapse or benefits can be suspended.'),
('lapse','insurance','policy lapse','A policy lapse occurs when coverage ends or becomes inactive because required premiums or conditions were not maintained. Reinstatement may be possible within a specified period and can require overdue premium, updated declarations, or fresh underwriting. Claims arising while coverage is inactive may not be payable.'),
('renewal','insurance','renewal','Renewal continues insurance for another term if the insurer and policyholder meet the renewal conditions. Premium, coverage, limits, exclusions, or terms can change at renewal depending on the product and risk experience. Customers should review the renewal notice rather than assuming the new term is identical.'),
('beneficiary','insurance','beneficiary','A beneficiary is a person or entity designated to receive certain insurance benefits, especially under life insurance. Policyholders should keep beneficiary names, identification details, relationships, allocation percentages, and contact information current. The policy rules and applicable law determine how benefits are handled if no valid beneficiary exists.'),
('rider','insurance','riders','A rider is an optional addition or amendment that changes the protection of a base insurance policy. Examples may include critical illness, accidental death, roadside assistance, or special property extensions. Riders can add premium, have separate limits or exclusions, and should be reviewed as carefully as the main policy.'),
('pre_existing','insurance','pre-existing conditions','A pre-existing condition is a health condition that existed or showed signs before the relevant coverage date, according to the policy definition. It may be excluded, covered after a waiting period, accepted with conditions, or handled differently after underwriting. Full and accurate disclosure is important.'),
('life','insurance','life insurance','Life insurance is designed to provide a financial benefit after an insured person dies and can sometimes include disability, accidental death, or critical illness features. Buyers should consider the amount dependents would need, policy term, affordability, exclusions, beneficiary arrangements, and whether medical underwriting is required.'),
('health','insurance','health insurance','Health insurance can help pay eligible medical expenses such as hospitalization, treatment, surgery, consultations, medicines, or other listed benefits. Key points to compare include network hospitals, cashless versus reimbursement claims, annual limits, room limits, co-payments, deductibles, waiting periods, pre-existing conditions, and exclusions.'),
('vehicle','insurance','vehicle insurance','Vehicle insurance can protect against insured damage to the vehicle, theft, third-party liability, and other selected risks. Important details include insured value, repair basis, approved workshops, deductible, driver restrictions, geographical limits, accessories, towing, and exclusions such as unlicensed driving or intentional damage.'),
('property','insurance','property insurance','Property insurance protects buildings, contents, equipment, or other insured property against specified causes of loss such as fire, storm, flood, theft, or accidental damage depending on the plan. Owners should insure realistic replacement values, understand exclusions and deductibles, and keep inventories, receipts, and photos for claims.'),
('business','insurance','business insurance','Business insurance can combine property, liability, business interruption, employee accident, stock, equipment, and other protections. The correct structure depends on the company’s activities, assets, revenue, locations, employees, contractual obligations, and major loss scenarios. Business interruption sums should be based on defensible financial records.'),
('travel','insurance','travel insurance','Travel insurance may cover eligible medical emergencies, trip cancellation, delays, baggage loss, personal liability, or evacuation depending on the plan. Customers should check destination limits, trip duration, pre-existing conditions, excluded activities, documentation requirements, and whether advisories or known events affect coverage.'),
('critical_illness','insurance','critical illness insurance','Critical illness insurance generally pays a defined benefit when a listed serious condition meets the policy definition. The diagnosis wording, severity thresholds, survival periods, waiting periods, exclusions, and number of covered illnesses matter. It is different from health insurance because the payout is often a lump sum rather than direct reimbursement of medical bills.'),
('personal_accident','insurance','personal accident insurance','Personal accident insurance can provide benefits for accidental death, disability, medical expenses, or other accident-related losses specified in the policy. It normally does not cover illness and may exclude hazardous activities or certain occupations unless declared or specifically covered.'),
('liability','insurance','liability insurance','Liability insurance helps protect an insured against covered legal liability to third parties for injury, property damage, or other defined losses. Policyholders should examine the limit, deductible, territorial scope, covered activities, defense costs, contractual liability rules, and exclusions.'),
('reinsurance','insurance','reinsurance','Reinsurance is insurance purchased by an insurer to transfer part of its own risk to another insurer or reinsurer. It helps manage large losses, catastrophe exposure, capital volatility, and portfolio concentration. It normally operates behind the scenes and does not replace the customer’s original policy relationship.'),
('fraud','insurance','insurance fraud','Insurance fraud involves intentional deception to obtain an improper insurance benefit or avoid a legitimate obligation. Examples include fabricated losses, inflated claims, staged events, false documents, or material misrepresentation. Fraud can lead to claim denial, policy cancellation, recovery action, or legal consequences.'),
('documents','insurance','insurance documents','Common insurance documents include identification, application forms, declarations, policy schedules, certificates, premium receipts, medical or inspection records, photographs, invoices, police reports, and claim forms. Exact requirements depend on the product and event, so the customer should follow the checklist shown for the specific application or claim.'),
('comparison','insurance','comparing plans','When comparing insurance plans, look beyond premium. Compare covered risks, benefit limits, deductibles or co-payments, exclusions, waiting periods, eligibility, claim procedures, payment frequency, network restrictions, service quality, renewal conditions, and how well the plan matches the loss you actually need to protect.'),
('claim_denial','insurance','claim denial','A claim can be denied when the event is outside coverage, the policy was inactive, an exclusion applies, required evidence is missing, a deductible exceeds the payable amount, fraud or material misrepresentation is found, or claim conditions were not met. The customer should request the reason, review the policy wording, provide missing evidence if allowed, and use the insurer’s review or complaint process if they disagree.'),
('claim_documents','insurance','claim documents','Claim documents vary by loss but commonly include the completed claim form, policy details, identification, proof of incident, receipts or invoices, medical reports, police or accident reports, photographs, repair estimates, ownership evidence, and bank details. Submitting clear, consistent records can reduce avoidable delays.'),
('claim_status','insurance','claim status','Claim status typically moves through stages such as submitted, under review, documents required, assessment, approved, rejected, or paid. If a claim remains pending, check whether the insurer requested additional information and confirm that all documents were received before escalating.'),
('cashless','insurance','cashless health claims','A cashless health claim is settled directly between the insurer or administrator and an eligible network hospital, subject to authorization and policy terms. The patient may still need to pay deductibles, co-payments, non-covered items, excess room charges, or expenses above the benefit limit.'),
('reimbursement','insurance','reimbursement claims','A reimbursement claim requires the insured to pay eligible costs first and then submit evidence for repayment under the policy. Original invoices, receipts, reports, prescriptions, and proof of payment are often important. Reimbursement is still subject to deductibles, limits, exclusions, and timely submission rules.'),
('free_look','insurance','free-look period','A free-look period allows a customer to review a newly issued policy for a specified number of days and cancel under the policy rules if it is unsuitable. Refund conditions can depend on whether coverage was used, administrative costs, or other contract terms.'),
('material_fact','insurance','material disclosure','A material fact is information that could reasonably affect underwriting, pricing, acceptance, exclusions, or claim assessment. Customers should answer application questions accurately and update the insurer when the policy requires notification of significant changes. Hiding important facts can jeopardize coverage.'),
('co_payment','insurance','co-payment','A co-payment or co-insurance requirement means the insured shares a percentage or fixed portion of eligible costs with the insurer. It can reduce premium but increases out-of-pocket expense. Customers should check whether it applies to all claims or only certain benefits, providers, or treatment types.'),
('depreciation','insurance','depreciation','Depreciation is a reduction in value due to age, wear, use, or obsolescence. Some property or vehicle claims are paid on depreciated value, while replacement-cost policies may use different rules. The settlement basis should be stated in the policy or claim calculation.'),
('salvage','insurance','salvage','Salvage is the remaining value of damaged insured property after a loss. Depending on policy terms, the insurer may take ownership of salvage after paying a total-loss claim or deduct salvage value if the policyholder keeps it.'),
('subrogation','insurance','subrogation','Subrogation allows an insurer that paid a covered claim to pursue a responsible third party to recover some or all of the payment. Policyholders generally should not waive recovery rights or settle with responsible parties in a way that harms the insurer’s rights without permission.'),
('indemnity','insurance','principle of indemnity','The principle of indemnity aims to restore the insured financially to approximately the position before a covered loss, rather than create a profit from the loss. It is common in property insurance, although some policies such as life or fixed-benefit products use stated benefits rather than pure indemnity.'),
]

website_topics = [
('home','website','home page','The public Home page is `/`. It should introduce the insurance portal, highlight major insurance categories, explain the main customer journey, and direct visitors to Plans, How It Works, Contact, Login, and Register. For a new visitor, the usual next step is to compare plans before creating an account.'),
('plans','website','plans page','The public Plans page is `/plans`. Customers can use it to review active insurance packages and compare information such as insurance type, coverage range, payment frequency, benefits, eligibility, exclusions, required documents, and terms when those fields are available.'),
('how_it_works','website','how it works','The How It Works page is `/how-it-works`. It should explain the end-to-end process: browse plans, register or log in, submit an application, complete review requirements, receive policy approval, pay premiums, manage the policy, and submit claims when needed.'),
('contact','website','contact support','The public Contact page is `/contact`. Use it when a visitor needs human assistance, has a question that requires staff review, or cannot resolve an account, policy, payment, or claim issue through the self-service pages.'),
('login','website','login','The Login page is `/login`. Users should sign in with their own account credentials and should never share passwords or one-time codes with the chatbot. If login fails, verify the email, password, account role, and account status, or use the password reset flow.'),
('register','website','registration','The Register page is `/register`. A new customer should create an account using accurate identity and contact information, then sign in and use the customer dashboard to apply for insurance. Duplicate or incorrect account information can cause later verification problems.'),
('forgot_password','website','forgot password','The Forgot Password page is `/forgot-password`. A user enters the registered email, follows the reset instructions, and chooses a new secure password. The chatbot should never request the old password, reset token, OTP, or full authentication secret.'),
('customer_dashboard','website','customer dashboard','The customer Dashboard is `/customer/dashboard`. It should summarize the customer’s insurance activity and provide access to Policies, Applications, Apply, Claims, Payments, Notifications, Feedback, and Profile.'),
('customer_policies','website','customer policies','Customer Policies are available at `/customer/policies`. This area is used to view issued or active policy information and related details. If a customer cannot see an expected policy, they should verify that the application was approved and that the policy was actually issued or activated.'),
('customer_applications','website','customer applications','Customer Applications are at `/customer/applications`. The customer can track application progress and see whether an application is pending, under review, approved, rejected, or requires additional information, depending on the status model used by the portal.'),
('customer_apply','website','apply for insurance','The insurance application page is `/customer/apply`. A logged-in customer selects an available plan, completes required form fields, uploads requested documents, reviews the information for accuracy, and submits. The application is not a guaranteed approval; staff or automated checks may review it.'),
('customer_claims','website','customer claims','Customer Claims are at `/customer/claims`. The page should show submitted claims and their status. Customers should use it to track review progress, see whether documents are missing, and understand whether a claim is pending, approved, rejected, or paid.'),
('submit_claim','website','submit claim','The Submit Claim page is `/customer/submit-claim`. A customer should choose the relevant policy, describe the insured event accurately, enter the requested dates and amounts, attach supporting evidence, and submit promptly. Final claim eligibility depends on policy coverage and review.'),
('payments','website','payments','Customer Payments are at `/customer/payments`. This section supports premium payment tracking and available payment methods. Customers should verify the policy or premium period, amount, payment method, reference, and verification status before assuming a payment has been accepted.'),
('notifications','website','notifications','Customer Notifications are at `/customer/notifications`. Important application, claim, payment, and policy updates can be surfaced there. Users should review unread notifications when a status appears unchanged or when staff may have requested more information.'),
('feedback','website','feedback','Customer Feedback is at `/customer/feedback`. It can collect ratings and comments to help the business analyze service quality without relying on unnecessary personal data. Admin analytics should focus on trends, themes, satisfaction, and operational improvements.'),
('profile','website','customer profile','Customer Profile is at `/customer/profile`. Users can review or update permitted personal details. Sensitive identity changes may require additional verification, and credentials such as passwords or OTPs should not be exposed through ordinary profile fields.'),
('agent_dashboard','website','agent dashboard','The Agent Dashboard is `/agent/dashboard`. It should give agents a working overview of assigned or relevant applications, claims, messages, notifications, and profile access so they can support customers efficiently.'),
('agent_applications','website','agent applications','Agent Applications are at `/agent/applications`. Agents can review relevant customer applications, verify completeness, request clarification where authorized, and support progression through the review workflow without making unsupported promises of approval.'),
('agent_claims','website','agent claims','Agent Claims are at `/agent/claims`. Agents can review assigned or relevant claims, inspect available evidence, communicate missing requirements, and support the claim workflow. Final decisions should follow company authority and policy rules.'),
('agent_messages','website','agent messages','Agent Messages are at `/agent/messages`. This supports structured communication with customers or internal users. Messages should avoid requesting passwords, OTPs, full card numbers, or other secrets and should keep a professional audit-friendly record.'),
('admin_dashboard','website','admin dashboard','The Admin Dashboard is `/admin/dashboard`. It should summarize important business metrics and provide links to insurance types, packages, users, applications, claims, payments, premium schedule, forms, notifications, feedback, payment methods, auto checks, reports, salary, predictions, and profile.'),
('admin_types','website','admin insurance types','Admin Insurance Types are at `/admin/insurance-types`. Authorized administrators can manage the high-level product categories used by packages and the website. Changes should be controlled because they can affect applications, reports, filtering, and historical consistency.'),
('admin_packages','website','admin packages','Admin Packages are at `/admin/packages`. This is where authorized staff manage plan configuration such as names, types, descriptions, coverage, premium parameters, benefits, eligibility, exclusions, required documents, and active status. Product changes should be versioned or audited when they affect existing customers.'),
('admin_users','website','admin users','Admin Users are at `/admin/users`. Authorized staff can review user accounts and roles. Access should follow least-privilege principles, and administrative actions affecting roles, status, or personal data should be auditable.'),
('admin_applications','website','admin applications','Admin Applications are at `/admin/applications`. Administrators can monitor and manage application workflow, investigate bottlenecks, verify supporting information, and coordinate review decisions according to business rules.'),
('admin_claims','website','admin claims','Admin Claims are at `/admin/claims`. Authorized staff can review claim status, evidence, decision workflow, and operational backlog. The system should preserve decision reasons and audit trails rather than silently changing outcomes.'),
('admin_payments','website','admin payments','Admin Payments are at `/admin/payments`. This area is used to review payment records, verification states, payment references, amounts, and exceptions. Payment reconciliation should be matched against trusted transaction evidence before confirming settlement.'),
('premium_schedule','website','premium schedule','Admin Premium Schedule is at `/admin/premium-schedule`. It supports configuration or review of premium-related scheduling. Changes that affect customer charges should be validated carefully, tested, and auditable.'),
('admin_forms','website','admin forms','Admin Forms are at `/admin/forms`. Form templates and fields should collect only necessary information, validate inputs, clearly label required fields, and remain consistent with the underwriting, application, or claim processes that consume them.'),
('admin_notifications','website','admin notifications','Admin Notifications are at `/admin/notifications`. Administrators can manage important communications and system notices. Notifications should be targeted, understandable, and tied to actionable events rather than overwhelming users with low-value messages.'),
('admin_feedback','website','admin feedback','Admin Feedback is at `/admin/feedback`. The business can analyze comments and ratings for recurring themes, customer pain points, service quality, and satisfaction trends. Analysis should avoid exposing unnecessary customer identity data.'),
('payment_methods','website','payment methods','Admin Payment Methods are at `/admin/payment-methods`. Authorized staff can configure which payment options are available. Each method should have clear instructions, validation, status handling, and reconciliation procedures.'),
('autocheck','website','auto check','Admin Auto Check is at `/admin/autocheck`. Automated checks can support consistency and speed, but results should be explainable, logged, and reviewable. Automation should not silently make high-impact decisions outside the authority defined by the business.'),
('reports','website','admin reports','Admin Reports are at `/admin/reports`. Reports should summarize business performance using efficient database queries and appropriate indexes, especially when datasets grow. Useful views can include applications, claims, payments, policy activity, conversion, service performance, and trends.'),
('salary','website','admin salary','Admin Salary is at `/admin/salary`. Salary information should be restricted to authorized roles, protected as sensitive data, and logged appropriately. Chatbot answers should never reveal another employee’s confidential salary details.'),
('predictions','website','admin predictions','Admin Predictions are at `/admin/predictions`. Predictive models should show input assumptions, output, confidence or evaluation metrics where available, and clear limitations. Predictions should support human decisions rather than be presented as guaranteed outcomes.'),
('privacy','website','privacy','The Privacy page is `/privacy`. The portal should explain what data is collected, why it is needed, how it is protected, how long it is retained, and what rights or contact channels users have. The chatbot should minimize sensitive-data collection and never request authentication secrets.'),
('terms','website','terms','The Terms page is `/terms`. It should set expectations for portal use, account responsibilities, acceptable behavior, and relevant legal terms. Insurance contract terms for a specific policy remain governed by the issued policy documents and applicable rules.'),
('security','website','website security','A secure insurance website should use authentication, role-based authorization, strong password handling, HTTPS in production, validation, secure file uploads, audit logging, database access controls, backups, dependency updates, and monitoring. Sensitive operations should never trust frontend role checks alone; the backend must enforce authorization.'),
('performance','website','website performance','Insurance portals can slow down as data grows if pages load large tables, run repeated queries, miss database indexes, or perform expensive analytics synchronously. Use pagination, filtered API queries, indexes on commonly searched/status/date fields, DTO projections, caching where safe, and background or precomputed aggregates for heavy reports.'),
('api','website','website API','A clean portal API should use predictable routes, validation, typed request/response structures, authorization, consistent error handling, pagination, and clear status codes. Avoid returning entire database entities when a smaller DTO is sufficient, especially on high-volume list pages.'),
('backup','website','backup and recovery','Business-critical insurance data should be backed up regularly and restoration should be tested. Backups should cover the database and essential uploaded documents, be protected from unauthorized access, and follow a retention plan appropriate for the business.'),
('audit','website','audit trail','An audit trail records who performed important actions, what changed, and when. It is especially useful for application decisions, claim decisions, payment verification, role changes, product changes, and sensitive administrative updates. Audit logs should be tamper-resistant and access-controlled.'),
]

business_topics = [
('customer_service','business','customer service','A strong insurance customer-service process gives clear explanations, sets realistic expectations, records interactions, protects personal data, and provides next steps. Staff should distinguish information from final underwriting or claim decisions and escalate cases that need authorized review.'),
('lead_conversion','business','lead conversion','Insurance lead conversion improves when the business reduces friction between interest and application: explain products simply, show transparent eligibility and documents, provide plan comparison, respond quickly, follow up appropriately, and make the digital application easy to complete.'),
('retention','business','customer retention','Insurance retention depends on trust, useful coverage, reliable service, fair claim handling, timely renewal reminders, payment convenience, and proactive support. Measuring lapse reasons and renewal behavior can reveal where customers are leaving the journey.'),
('cross_sell','business','cross selling','Cross-selling should be needs-based rather than aggressive. Use existing customer context to identify genuine protection gaps, explain the additional value and cost, and let the customer decide. Avoid implying that unrelated products are mandatory.'),
('complaints','business','complaint handling','A good complaint process acknowledges the issue, records it, categorizes severity, investigates facts, communicates expected next steps, provides a reasoned outcome, and preserves escalation options. Complaint analytics can identify recurring operational defects.'),
('sla','business','service levels','Service-level targets help the business manage response time for applications, claims, payments, support, and document review. Useful SLAs should be measurable, realistic, monitored by stage, and paired with escalation rules when work becomes overdue.'),
('kpi','business','insurance KPIs','Useful insurance portal KPIs can include quote-to-application conversion, application approval rate, processing time, policy activation rate, premium collection rate, lapse rate, claim frequency, claim turnaround time, loss ratio, customer satisfaction, complaint volume, and digital self-service adoption.'),
('analytics','business','business analytics','Business analytics should turn portal data into decisions. Segment metrics by product, channel, time, customer journey stage, and operational team where appropriate. Use trends and cohorts rather than relying on one headline number, and validate data quality before acting on conclusions.'),
('marketing','business','insurance marketing','Insurance marketing works best when it explains customer problems and protection outcomes in plain language. Content can educate people about risks, compare product types, explain claims, clarify exclusions, and guide them to a suitable plan without making misleading promises.'),
('content','business','website content','Insurance website content should be simple, accurate, bilingual where needed, and action-oriented. Explain benefits together with important limits or exclusions, use examples carefully, define technical terms, and provide the next step such as compare plans, apply, upload documents, or contact support.'),
('seo','business','SEO','Insurance SEO should target helpful search intent such as what a product covers, how claims work, required documents, premium factors, and common customer questions. High-quality original explanations, clear page structure, fast performance, and trustworthy product information are more sustainable than keyword stuffing.'),
('sales_agent','business','agent productivity','Agent productivity improves with prioritized work queues, complete customer information, templates for routine communication, reminders for missing documents, clear authority levels, and dashboards showing overdue applications or claims. Automation should remove repetitive work without hiding important judgment.'),
('payment_ops','business','payment operations','Payment operations should reconcile customer payment records with trusted evidence, detect duplicates or mismatches, track verification status, and provide a clear exception workflow. Finance-sensitive actions should be logged and restricted to authorized users.'),
('claims_ops','business','claims operations','Efficient claims operations combine clear intake requirements, document checklists, triage, assignment, assessment, fraud controls, decision reasons, payment coordination, and customer communication. Track turnaround time by stage to identify bottlenecks rather than only measuring total duration.'),
('underwriting_ops','business','underwriting operations','Underwriting operations benefit from standardized data, risk rules, evidence checklists, referral thresholds, explainable automation, and audit trails. Simple cases can be accelerated while complex or high-risk cases are routed to experienced reviewers.'),
('data_quality','business','data quality','Insurance analytics and automation are only as reliable as the underlying data. Validate required fields, normalize statuses, prevent duplicate records, define ownership for corrections, monitor missing values, and keep historical changes when they affect reporting or decisions.'),
('fraud_ops','business','fraud controls','Fraud controls should combine rules, anomaly indicators, document validation, duplicate detection, behavioral signals, and human review. A fraud score is a risk signal, not proof of wrongdoing, so high-impact actions should use evidence and authorized review.'),
('ai_governance','business','AI governance','AI used in insurance should have a defined purpose, documented inputs, evaluation metrics, access controls, monitoring, human review for high-impact decisions, and safeguards against fabricated information. The chatbot should cite portal facts from trusted data and clearly separate guidance from binding decisions.'),
('rag','business','RAG chatbot','A retrieval-augmented chatbot searches a trusted knowledge base for relevant information and gives those results to the language model before it answers. This is useful for an insurance portal because website routes, company procedures, and product facts can remain grounded while the model still responds naturally.'),
('fine_tuning','business','AI fine tuning','Fine-tuning changes a model’s learned behavior by training on curated examples, while RAG supplies external knowledge at answer time. For a company chatbot, RAG is usually the safer first step for changing facts because the knowledge base can be updated without retraining the model.'),
('evaluation','business','chatbot evaluation','A business chatbot should be evaluated for answer correctness, grounding, helpfulness, safety, language quality, retrieval relevance, latency, and escalation behavior. Maintain a test set of real customer questions and track failures by category so improvements are measurable.'),
('handoff','business','human handoff','Human handoff is important when a customer needs an authorized decision, disputes a claim, has a payment issue, reports security concerns, or the chatbot lacks enough reliable information. The handoff should preserve conversation context so the customer does not need to repeat everything.'),
('privacy_ops','business','data privacy operations','Data privacy operations should minimize collection, restrict access by role, protect sensitive fields, define retention, log important access, and provide procedures for correction or deletion when applicable. Analytics should avoid using personal identity when aggregated insights are sufficient.'),
('business_continuity','business','business continuity','Insurance systems need business-continuity planning for outages, database failures, cyber incidents, and third-party service disruptions. Maintain backups, recovery procedures, alternative communication paths, incident ownership, and tested restoration priorities for critical customer functions.'),
('reporting','business','management reporting','Management reporting should connect metrics to action. Show current values, trends, targets, segmentation, anomalies, and operational owners. Reports should use consistent definitions so application, claim, payment, and policy numbers match across dashboards.'),
('database_scale','business','database scaling','As insurance datasets grow, database performance depends on indexes, query design, pagination, data types, connection pooling, archival strategy, and avoiding full-table scans. Heavy analytics can use summary tables or scheduled snapshots while operational screens query only the rows they need.'),
]

all_topics = insurance_topics + website_topics + business_topics

en_patterns = [
'What is {topic}?','Explain {topic} in simple terms.','Can you explain {topic} in detail?','How does {topic} work?','Why is {topic} important?','What should a customer know about {topic}?','What are the main points about {topic}?','Give me a practical explanation of {topic}.','What mistakes should I avoid with {topic}?','How should I understand {topic} before buying insurance?','What are common questions about {topic}?','Explain {topic} with an example.','How can {topic} affect a customer?','What should an insurance agent explain about {topic}?','What should an admin know about {topic}?','How do I check {topic} properly?','What are the risks related to {topic}?','What are best practices for {topic}?','How is {topic} handled in an insurance company?','What happens if there is a problem with {topic}?',
]
my_patterns = [
'{topic} ဆိုတာဘာလဲ။','{topic} ကို ရိုးရိုးရှင်းရှင်းရှင်းပြပါ။','{topic} အကြောင်း အသေးစိတ်ရှင်းပြပါ။','{topic} က ဘယ်လိုအလုပ်လုပ်လဲ။','{topic} က ဘာကြောင့်အရေးကြီးလဲ။','Customer တစ်ယောက်အနေနဲ့ {topic} အကြောင်း ဘာတွေသိထားသင့်လဲ။','{topic} ရဲ့ အဓိကအချက်တွေက ဘာတွေလဲ။','{topic} ကို လက်တွေ့နားလည်အောင်ရှင်းပြပါ။','{topic} နဲ့ပတ်သက်ပြီး ဘာအမှားတွေရှောင်သင့်လဲ။','Insurance ဝယ်ခင် {topic} ကို ဘယ်လိုနားလည်ထားသင့်လဲ။','{topic} နဲ့ပတ်သက်တဲ့ မေးခွန်းတွေကိုရှင်းပြပါ။','{topic} ကို ဥပမာနဲ့ရှင်းပြပါ။','{topic} က customer ကို ဘယ်လိုသက်ရောက်နိုင်လဲ။','Agent က {topic} ကို customer ကို ဘယ်လိုရှင်းပြသင့်လဲ။','Admin တစ်ယောက်အနေနဲ့ {topic} ကို ဘာသိထားသင့်လဲ။','{topic} ကို မှန်မှန်ကန်ကန်ဘယ်လိုစစ်မလဲ။','{topic} နဲ့ဆိုင်တဲ့ risk တွေကဘာလဲ။','{topic} အတွက် best practice တွေဘာလဲ။','Insurance company ထဲမှာ {topic} ကို ဘယ်လိုကိုင်တွယ်လဲ။','{topic} မှာပြဿနာဖြစ်ရင် ဘာလုပ်သင့်လဲ။',
]
contexts_en = [
'for a first-time customer','for an existing policyholder','for a family','for a small business owner','for an insurance agent','for an admin user','when comparing two plans','before submitting an application','after a policy is issued','when preparing a claim','when a payment is pending','when a customer is confused','when documents are missing','when the customer wants a quick answer','when the customer wants a detailed answer','for a Myanmar insurance portal','for online self-service','for a high-value policy','for a low-budget customer','for risk management'
]
contexts_my = [
'ပထမဆုံးအာမခံဝယ်မယ့် customer အတွက်','လက်ရှိ policyholder အတွက်','မိသားစုအတွက်','SME business owner အတွက်','insurance agent အတွက်','admin user အတွက်','plan နှစ်ခုနှိုင်းယှဉ်တဲ့အခါ','application မတင်ခင်','policy ထုတ်ပြီးတဲ့နောက်','claim ပြင်ဆင်တဲ့အခါ','payment pending ဖြစ်နေတဲ့အခါ','customer နားမလည်တဲ့အခါ','documents မပြည့်စုံတဲ့အခါ','အတိုချုံးနားလည်ချင်တဲ့အခါ','အသေးစိတ်နားလည်ချင်တဲ့အခါ','Myanmar insurance portal အတွက်','online self-service သုံးတဲ့အခါ','coverage မြင့်တဲ့ policy အတွက်','budget နည်းတဲ့ customer အတွက်','risk management အတွက်'
]
qualifiers_en = ['step by step','with key risks','with a simple example','with best practices','with customer next steps','with agent next steps','with admin considerations','without technical jargon','including common mistakes','including important limitations']
qualifiers_my = ['အဆင့်လိုက်','risk အချက်တွေနဲ့','ရိုးရိုးဥပမာနဲ့','best practice တွေနဲ့','customer ဘာဆက်လုပ်ရမလဲပါထည့်ပြီး','agent ဘာဆက်လုပ်ရမလဲပါထည့်ပြီး','admin စဉ်းစားရမယ့်အချက်တွေနဲ့','နည်းပညာစကားမများဘဲ','အဖြစ်များတဲ့အမှားတွေပါထည့်ပြီး','အရေးကြီး limitation တွေပါထည့်ပြီး']

# Expand topic labels into mixed Myanmar-friendly names for question variety.
my_topic_alias = {
'insurance basics':'အာမခံအခြေခံ','premium':'Premium ပရီမီယံ','coverage':'Coverage အာမခံကာကွယ်မှု','deductible':'Deductible','exclusions':'Exclusion မပါဝင်သည့်အချက်များ','waiting period':'Waiting Period','claims':'Claim','underwriting':'Underwriting','policy limits':'Policy Limit','sum insured':'Sum Insured','grace period':'Grace Period','policy lapse':'Policy Lapse','renewal':'Renewal','beneficiary':'Beneficiary','riders':'Insurance Rider','pre-existing conditions':'Pre-existing Condition','life insurance':'Life Insurance','health insurance':'Health Insurance','vehicle insurance':'Vehicle Insurance','property insurance':'Property Insurance','business insurance':'Business Insurance','travel insurance':'Travel Insurance','critical illness insurance':'Critical Illness Insurance','personal accident insurance':'Personal Accident Insurance','liability insurance':'Liability Insurance','reinsurance':'Reinsurance','insurance fraud':'Insurance Fraud','insurance documents':'Insurance Documents','comparing plans':'Insurance Plan နှိုင်းယှဉ်ခြင်း','claim denial':'Claim Denial','claim documents':'Claim Documents','claim status':'Claim Status','cashless health claims':'Cashless Claim','reimbursement claims':'Reimbursement Claim','free-look period':'Free-look Period','material disclosure':'Material Disclosure','co-payment':'Co-payment','depreciation':'Depreciation','salvage':'Salvage','subrogation':'Subrogation','principle of indemnity':'Indemnity Principle',
}

def answer_for(base, domain, context, qualifier, lang):
    if lang == 'en':
        tail = f" In the context of {context}, apply this by checking the exact policy or portal record, keeping supporting evidence, and following the next authorized step. {qualifier.capitalize()} means the explanation should stay practical and should not promise approval, claim payment, or a binding quote unless the authorized company process confirms it."
        if domain == 'website':
            tail = f" For {context}, use the route and workflow above, verify the user has the correct role, and check status or validation messages before retrying. {qualifier.capitalize()}; never request passwords, OTPs, or full card details in chat."
        elif domain == 'business':
            tail = f" For {context}, turn this into a measurable workflow with clear ownership, status definitions, auditability, and customer-safe communication. {qualifier.capitalize()}; use data to support decisions but keep human review for high-impact exceptions."
    else:
        tail = f" {context} ဆိုတဲ့အခြေအနေမှာ သက်ဆိုင်ရာ policy သို့မဟုတ် portal record ကိုအရင်စစ်ပြီး supporting evidence ကိုပြည့်စုံအောင်ထားကာ authorized process အတိုင်းဆက်လုပ်သင့်ပါတယ်။ {qualifier} ရှင်းပြရာမှာ approval၊ claim payment သို့မဟုတ် final quote ကို company reviewer မအတည်ပြုမချင်း အာမခံမပြောသင့်ပါဘူး။"
        if domain == 'website':
            tail = f" {context} ဆိုတဲ့အခြေအနေမှာ အပေါ်က route/workflow ကိုသုံးပြီး user role မှန်မမှန်၊ status နဲ့ validation message တွေကိုစစ်ပါ။ {qualifier} ရှင်းပြနိုင်ပေမယ့် password၊ OTP၊ full card number ကို chat ထဲမှာမတောင်းသင့်ပါဘူး။"
        elif domain == 'business':
            tail = f" {context} ဆိုတဲ့အခြေအနေမှာ ဒီအချက်ကို measurable workflow အဖြစ်ပြောင်းပြီး owner၊ status definition၊ audit trail နဲ့ customer communication ကိုရှင်းလင်းထားသင့်ပါတယ်။ {qualifier} လုပ်နိုင်ပေမယ့် high-impact exception တွေမှာ human review ထားသင့်ပါတယ်။"
    return base + tail

rows=[]
seen=set()
# Target distribution exact: 25k insurance, 15k website, 10k business
quotas={'insurance':25000,'website':15000,'business':10000}
by_domain={d:[t for t in all_topics if t[1]==d] for d in quotas}

for domain, quota in quotas.items():
    topics=by_domain[domain]
    idx=0
    attempts=0
    while idx < quota:
        attempts += 1
        topic_id, dom, topic, base = topics[idx % len(topics)]
        # deterministic variety using mixed radix
        j = idx // len(topics)
        lang = 'en' if (j % 5) < 3 else 'my'  # ~60/40 EN/MY
        pidx = (j*3 + idx) % 20
        cidx = (j*7 + idx//3) % 20
        qidx = (j*11 + idx//5) % 10
        if lang=='en':
            pat=en_patterns[pidx]; context=contexts_en[cidx]; qual=qualifiers_en[qidx]; label=topic
            q=pat.format(topic=label)
            # Add context/qualifier to ensure uniqueness and realistic phrasing.
            if j % 2 == 0: q += f" Please answer {qual} {context}."
            else: q += f" I need this {context}, {qual}."
        else:
            pat=my_patterns[pidx]; context=contexts_my[cidx]; qual=qualifiers_my[qidx]; label=my_topic_alias.get(topic, topic)
            q=pat.format(topic=label)
            if j % 2 == 0: q += f" {context} {qual} ရှင်းပြပေးပါ။"
            else: q += f" {context} ဆိုရင် {qual} ပြောပေးပါ။"
        # collision fallback
        if q in seen:
            q += f" Case {j+1}."
        seen.add(q)
        answer=answer_for(base, domain, context, qual, lang)
        keywords=' '.join(sorted(set(re.findall(r"[A-Za-z0-9_/.-]{3,}", (topic+' '+topic_id+' '+q).lower())))[:25])
        route=''
        m=re.search(r'`(/[^`]+)`', base)
        if m: route=m.group(1)
        rows.append({
            'id':f'QA{len(rows)+1:05d}', 'domain':domain, 'category':topic_id, 'intent':topic_id,
            'language':lang, 'question':q, 'answer':answer, 'keywords':keywords,
            'source_type':'curated_template', 'route':route
        })
        idx+=1

assert len(rows)==50000
assert len({r['question'] for r in rows})==50000

tsv=OUT/'insurance_website_qa_50000.tsv'
with tsv.open('w',encoding='utf-8',newline='') as f:
    w=csv.DictWriter(f,fieldnames=list(rows[0]),delimiter='\t',lineterminator='\n',quoting=csv.QUOTE_MINIMAL)
    w.writeheader(); w.writerows(rows)

csvp=Path('/mnt/data/insurance_website_business_qa_50000.csv')
with csvp.open('w',encoding='utf-8-sig',newline='') as f:
    w=csv.DictWriter(f,fieldnames=list(rows[0]),lineterminator='\n')
    w.writeheader(); w.writerows(rows)

jsonlp=Path('/mnt/data/insurance_website_business_qa_50000.jsonl')
with jsonlp.open('w',encoding='utf-8') as f:
    for r in rows:
        f.write(json.dumps(r,ensure_ascii=False)+'\n')

meta={
  'total':50000,'distribution':{d:sum(r['domain']==d for r in rows) for d in quotas},
  'languages':{l:sum(r['language']==l for r in rows) for l in ['en','my']},
  'fields':list(rows[0]),'generated_for':'DICP Insurance Portal AI Assistant',
  'method':'Curated topic templates + scenario variation for local RAG retrieval; not a claim of neural-network fine-tuning.'
}
(OUT/'knowledge_metadata.json').write_text(json.dumps(meta,ensure_ascii=False,indent=2),encoding='utf-8')
Path('/mnt/data/insurance_website_business_qa_50000_metadata.json').write_text(json.dumps(meta,ensure_ascii=False,indent=2),encoding='utf-8')
print(meta)
print('tsv bytes',tsv.stat().st_size,'csv bytes',csvp.stat().st_size,'jsonl bytes',jsonlp.stat().st_size)
print('sample',rows[0])
